### ISSUE TITLE
Browser Tab title shows "Panda Testzone" instead of "floatpoint"

### ISSUE THREAD

**Issue by Balaguru4580** [Balaguru4580/floatpoint#1]
The browser tab when opening the HTML file shows "Panda Testzone" which is a placeholder I used. 

It needs to be changed so that it says "floatpoint" instead!

**Comment by parulgupta26** [comment]
Hey @Balaguru4580 I'd like to take this up. Please assign to me.

**Comment by parulgupta26** [comment]
@Balaguru4580  Kindly review my PR - https://github.com/Balaguru4580/floatpoint/pull/4

**Comment by parulgupta26** [comment]
@Balaguru4580 Since the PR is merged, you can mark this issue as closed :)

**Comment by parulgupta26** [comment]
@Balaguru4580  Since the PR is merged, you might want to mark this issue as closed :)

**Comment by Balaguru4580** [comment]
> @Balaguru4580  Since the PR is merged, you might want to mark this issue as closed :)


I forgot and went to sleep 😂

Appreciate the heads up!
