### ISSUE TITLE
Scrolling occurs due to animation of symbol.

### ISSUE THREAD

**Issue by Balaguru4580** [Balaguru4580/floatpoint#2]
When the Yin - Yang Symbol hovers up and down in the webpage, the entire webpage extends, hence causing the scrollbar also to elongate along with it, which is very distracting.

This probably involves setting a hard size limit to that div, or maybe another solution!

**Comment by hemantwasthere** [comment]
Hey @Balaguru4580 ,  I would like to work on this issue
